package com.bqsummer.controller;

import com.bqsummer.common.dto.recharge.RechargeOrder;
import com.bqsummer.common.vo.req.recharge.CreateRechargeRequest;
import com.bqsummer.common.vo.resp.recharge.CreateRechargeResponse;
import com.bqsummer.service.recharge.RechargeService;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/api/v1/recharge")
@RequiredArgsConstructor
public class RechargeController {

    private final RechargeService rechargeService;

    @PostMapping("/create")
    public ResponseEntity<CreateRechargeResponse> create(@Valid @RequestBody CreateRechargeRequest request) {
        return ResponseEntity.ok(rechargeService.create(request));
    }

    @GetMapping("/order/{orderNo}")
    public ResponseEntity<RechargeOrder> get(@PathVariable String orderNo) {
        return ResponseEntity.ok(rechargeService.getByOrderNo(orderNo));
    }

    // Mock payment success endpoint generated by MockPaymentChannel payUrl
    @GetMapping("/mockpay/{orderNo}")
    public ResponseEntity<String> mockPay(@PathVariable String orderNo) {
        rechargeService.mockPaySuccess(orderNo);
        return ResponseEntity.ok("PAID");
    }
}

